package com.toolformoney.investarget.bank.sberbank;

import com.google.inject.Singleton;
import com.toolformoney.Currency;
import com.toolformoney.model.InvestmentTargetLoader;
import com.toolformoney.model.InvestmentTypeName;
import com.toolformoney.model.bank.Bank;
import com.toolformoney.model.bank.BankOfferProfit;
import com.toolformoney.model.bank.BankOfferRisk;
import com.toolformoney.model.pamm.InvestmentTargetOffer;
import com.toolformoney.utils.Constants;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * http://sberbank.ru/
 * Author Dmitriy Liandres
 * Date 06.06.2016
 */
@Singleton
public class SberbankLoader extends InvestmentTargetLoader<Bank> {

    private static final Logger logger = LoggerFactory.getLogger(SberbankLoader.class);

    @Override
    public List<Bank> load() throws IOException {
        logger.info("Start download all sberbank.ru offers");
        List<Bank> banks = new ArrayList<>();
        //add offer in usd

        Bank sperbank = new Bank("Сбербанк", "/vklady-investitsii/banki/sberbank/");

        //RUB
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 1000., 100000., Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 5.5)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 1000., 100000., Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 5.9)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 1000., 100000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.3)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 1000., 100000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.7)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 1000., 100000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.8)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 1000., 100000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.65)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 1000., 100000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.5)));

        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100000., 400000., Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 5.65)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100000., 400000., Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.05)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100000., 400000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.45)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100000., 400000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.85)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100000., 400000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.95)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100000., 400000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.8)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100000., 400000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.65)));

        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 400000., 700000., Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 5.8)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 400000., 700000., Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.2)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 400000., 700000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.6)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 400000., 700000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.0)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 400000., 700000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.1)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 400000., 700000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.95)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 400000., 700000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.8)));

        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 700000., 2000_000., Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.0)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 700000., 2000_000., Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.4)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 700000., 2000_000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.8)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 700000., 2000_000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.2)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 700000., 2000_000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.3)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 700000., 2000_000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.15)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 700000., 2000_000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.)));

        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 2000_000., null, Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.0)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 2000_000., null, Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.4)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 2000_000., null, Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.8)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 2000_000., null, Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.2)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 2000_000., null, Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.3)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 2000_000., null, Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.15)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 2000_000., null, Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.)));

        //USD
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100., 3000., Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100., 3000., Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100., 3000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100., 3000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.65)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100., 3000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.25)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100., 3000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.5)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100., 3000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.6)));

        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 3000., 10000., Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 3000., 10000., Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 3000., 10000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.05)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 3000., 10000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.7)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 3000., 10000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.35)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 3000., 10000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.6)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 3000., 10000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.7)));

        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 10000., 20000., Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 10000., 20000., Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 10000., 20000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.2)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 10000., 20000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.85)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 10000., 20000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.5)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 10000., 20000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.75)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 10000., 20000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.85)));

        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 20000., 100_000., Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.05)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 20000., 100_000., Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.15)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 20000., 100_000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.4)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 20000., 100_000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.0)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 20000., 100_000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.65)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 20000., 100_000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.9)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 20000., 100_000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 2.0)));

        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100_000., null, Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.05)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100_000., null, Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.15)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100_000., null, Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.4)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100_000., null, Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.0)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100_000., null, Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.65)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100_000., null, Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.9)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100_000., null, Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 2.0)));

        //EUR
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100., 3000., Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100., 3000., Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100., 3000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100., 3000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100., 3000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100., 3000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.15)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100., 3000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.2)));

        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 3000., 10000., Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 3000., 10000., Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 3000., 10000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 3000., 10000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 3000., 10000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.15)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 3000., 10000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.3)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 3000., 10000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.35)));

        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 10000., 20000., Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 10000., 20000., Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 10000., 20000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 10000., 20000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 10000., 20000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.3)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 10000., 20000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.45)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 10000., 20000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.5)));

        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 20000., 100_000., Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 20000., 100_000., Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 20000., 100_000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 20000., 100_000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.1)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 20000., 100_000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.45)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 20000., 100_000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.6)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 20000., 100_000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.65)));

        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100_000., null, Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100_000., null, Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100_000., null, Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100_000., null, Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.1)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100_000., null, Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.45)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100_000., null, Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.6)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй", 100_000., null, Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.65)));


        //RUB
        //-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 1000., 100000., Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 5.7)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 1000., 100000., Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.1)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 1000., 100000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.5)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 1000., 100000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.9)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 1000., 100000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.0)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 1000., 100000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.85)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 1000., 100000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.7)));

        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100000., 400000., Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.0)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 100000., 400000., Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.4)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100000., 400000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.8)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100000., 400000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.2)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100000., 400000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.3)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100000., 400000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.15)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100000., 400000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.0)));

        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 400000., 700000., Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.2)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 400000., 700000., Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.6)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 400000., 700000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.0)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 400000., 700000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.4)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 400000., 700000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.5)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 400000., 700000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.35)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 400000., 700000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.2)));

        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 700000., 2000_000., Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.4)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 700000., 2000_000., Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.8)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 700000., 2000_000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.2)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 700000., 2000_000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.6)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 700000., 2000_000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.7)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 700000., 2000_000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.55)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 700000., 2000_000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.4)));

        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 2000_000., null, Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.4)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 2000_000., null, Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.8)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 2000_000., null, Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.2)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 2000_000., null, Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.6)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 2000_000., null, Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.7)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 2000_000., null, Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.55)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 2000_000., null, Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 7.4)));

        //USD
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100., 3000., Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100., 3000., Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100., 3000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.2)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100., 3000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.85)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100., 3000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.5)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100., 3000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.75)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100., 3000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.85)));

        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 3000., 10000., Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 3000., 10000., Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 3000., 10000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.3)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 3000., 10000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.95)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 3000., 10000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.6)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 3000., 10000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.85)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 3000., 10000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.95)));

        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 10000., 20000., Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 10000., 20000., Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 10000., 20000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.45)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 10000., 20000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.1)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 10000., 20000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.75)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 10000., 20000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 2.0)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 10000., 20000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 2.1)));

        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 20000., 100_000., Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.1)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 20000., 100_000., Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.25)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 20000., 100_000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.6)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 20000., 100_000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.25)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 20000., 100_000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.9)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 20000., 100_000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 2.15)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 20000., 100_000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 2.25)));

        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100_000., null, Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.1)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100_000., null, Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.25)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100_000., null, Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.6)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100_000., null, Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.25)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100_000., null, Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.9)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100_000., null, Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 2.15)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100_000., null, Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 2.25)));

        //EUR
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100., 3000., Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100., 3000., Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100., 3000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100., 3000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100., 3000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.25)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100., 3000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.4)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100., 3000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.45)));

        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 3000., 10000., Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 3000., 10000., Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 3000., 10000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 3000., 10000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.05)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 3000., 10000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.45)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 3000., 10000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.55)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 3000., 10000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.60)));

        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 10000., 20000., Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 10000., 20000., Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 10000., 20000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.05)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 10000., 20000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.2)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 10000., 20000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.6)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 10000., 20000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.7)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 10000., 20000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.75)));

        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 20000., 100_000., Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 20000., 100_000., Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 20000., 100_000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.1)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 20000., 100_000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.35)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 20000., 100_000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.7)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 20000., 100_000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.85)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 20000., 100_000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.9)));

        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100_000., null, Constants.DAYS_PER_MONTH, Constants.DAYS_PER_MONTH * 2, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100_000., null, Constants.DAYS_PER_MONTH * 2, Constants.DAYS_PER_MONTH * 3, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100_000., null, Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.1)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100_000., null, Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.35)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100_000., null, Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.7)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100_000., null, Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.85)));
        sperbank.addOffer(new InvestmentTargetOffer("Сохраняй ОнЛ@йн", 100_000., null, Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.9)));
        //-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        //-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        //RUB
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 1000., 100000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.05)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 1000., 100000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.45)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 1000., 100000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.25)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 1000., 100000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.1)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 1000., 100000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 5.95)));

        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 100000., 400000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.2)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 100000., 400000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.6)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 100000., 400000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.4)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 100000., 400000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.25)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 100000., 400000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.1)));

        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 400000., 700000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.35)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 400000., 700000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.75)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 400000., 700000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.55)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 400000., 700000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.4)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 400000., 700000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.25)));

        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 700000., 2000_000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.55)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 700000., 2000_000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.95)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 700000., 2000_000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.75)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 700000., 2000_000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.6)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 700000., 2000_000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.45)));

        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 2000_000., null, Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.55)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 2000_000., null, Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.95)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 2000_000., null, Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.75)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 2000_000., null, Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.6)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 2000_000., null, Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.RUB, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 6.45)));

        //USD
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 100., 3000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 100., 3000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.6)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 100., 3000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.15)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 100., 3000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.35)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 100., 3000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.4)));

        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 3000., 10000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 3000., 10000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.65)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 3000., 10000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.25)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 3000., 10000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.45)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 3000., 10000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.5)));

        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 10000., 20000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.15)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 10000., 20000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.8)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 10000., 20000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.4)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 10000., 20000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.6)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 10000., 20000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.65)));

        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 20000., 100_000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.35)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 20000., 100_000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.95)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 20000., 100_000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.55)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 20000., 100_000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.75)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 20000., 100_000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.8)));

        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 100_000., null, Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.35)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 100_000., null, Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.95)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 100_000., null, Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.55)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 100_000., null, Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.75)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 100_000., null, Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.USD, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 1.8)));

        //EUR
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 100., 3000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 100., 3000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 100., 3000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 100., 3000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.05)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 100., 3000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.1)));

        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 3000., 10000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 3000., 10000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 3000., 10000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.05)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 3000., 10000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.2)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 3000., 10000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.25)));

        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 10000., 20000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 10000., 20000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 10000., 20000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.2)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 10000., 20000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.35)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 10000., 20000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.4)));

        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 20000., 100_000., Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 20000., 100_000., Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.05)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 20000., 100_000., Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.35)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 20000., 100_000., Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.5)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 20000., 100_000., Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.55)));

        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 100_000., null, Constants.DAYS_PER_MONTH * 3, Constants.DAYS_PER_MONTH * 6, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.01)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 100_000., null, Constants.DAYS_PER_MONTH * 6, Constants.DAYS_PER_MONTH * 12, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.05)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 100_000., null, Constants.DAYS_PER_MONTH * 12, Constants.DAYS_PER_MONTH * 24, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.35)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 100_000., null, Constants.DAYS_PER_MONTH * 24, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.50)));
        sperbank.addOffer(new InvestmentTargetOffer("Пополняй", 100_000., null, Constants.DAYS_PER_MONTH * 36, Constants.DAYS_PER_MONTH * 36, 0., "http://sberbank.ru/ru/person/contributions/deposits/save", Currency.EUR, null, new BankOfferRisk(0.1), new BankOfferProfit(true, 0.55)));


        banks.add(sperbank);

        logger.info("Finish download all sberbank.ru offers");
        return banks;
    }

    @Override
    public InvestmentTypeName getInvestmentTypeName() {
        return InvestmentTypeName.SBERBANK;
    }
}
